creation_rules:
 - path_regex: ^hosts/secrets.yaml$
   key_groups:
    - age:
      - age15qprsda4w5jmefadmnz27qatjc5v56ptgeyj3qrvwdfw76rzgu4s88cu7q
      - age1ydp7sku0ayvdphvrgvn3r5ets37ned6x5ky3hkc2hw8huanakvqstx3c94
      - age1ptt07r2e2eaf4x0wvwxn3dpa0j9td6t8y590z062rrd073fy5pfqehaagw
