devbox:
  nixos-rebuild switch --flake .#devbox --target-host devbox-root

qemu-firmware:
  ./gen-qemu-firmware.sh

qemu-devvm:
  qemu-system-aarch64 -M virt \
    -cpu max -smp 2 -m 4096 \
    -nographic \
    -drive if=pflash,format=raw,file=efi.img,readonly=on \
    -drive if=pflash,format=raw,file=varstore.img \
    -drive if=virtio,format=qcow2,file=devvm.qcow2 \
    -device virtio-scsi-pci,id=scsi0 -device scsi-cd,drive=cd,bootindex=0 -drive if=none,id=cd,file=nixos-minimal-aarch64-linux.iso

devvm:
  nixos-rebuild build-vm --flake .#devvm && ./result/bin/run-unnamed-vm
