# See https://github.com/NixOS/nixpkgs/issues/177873 for why this command is like this
devbox:
  nixos-rebuild switch --fast --flake .#devbox --build-host devbox-root --target-host devbox-root

run-qemu:
  qemu-system-aarch64 -M virt \
    -cpu max -smp 2 -m 8192 \
    -object rng-random,filename=/dev/urandom,id=rng0 \
    -device virtio-rng-pci,rng=rng0 \
    -device virtio-net-pci,netdev=net0 \
    -netdev user,id=net0,hostfwd=tcp::8022-:22 \
    -nographic \
    -drive if=pflash,format=raw,file=efi.img,readonly=on \
    -drive if=pflash,format=raw,file=varstore.img \
    -drive if=virtio,format=qcow2,file=qemu.qcow2 \
    # -device virtio-scsi-pci,id=scsi0 -device scsi-cd,drive=cd,bootindex=0 -drive if=none,id=cd,file=nixos-minimal-aarch64-linux.iso

switch-qemu:
  nixos-rebuild switch --flake .#qemu-aarch64 --target-host localhost-qemu |& nom

anywhere-qemu:
  nix run github:nix-community/nixos-anywhere -- -i ~/.ssh/id_ed25519 --flake .#qemu-aarch64 localhost-qemu \
    --debug \
    --kexec "$(nix build --print-out-paths github:nix-community/nixos-images#packages.aarch64-linux.kexec-installer-nixos-stable)/nixos-kexec-installer-aarch64-linux.tar.gz"

devvm:
  nixos-rebuild build-vm --flake .#devvm && ./result/bin/run-unnamed-vm
