version: "2.4"

volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      driver: journald
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    ports:
      - "8080:80"
    environment:
      TZ: America/New_York
      CRON_MIN: "3,33"
      PUBLISHED_PORT: 8080
      # ADMIN_EMAIL
      # ADMIN_PASSWORD
      # ADMIN_API_PASSWORD
      SERVER_DNS: freshrss.wolfgirl.dev
